#' Two observers, binary reliability data, section 11.3.1 from Krippendorff 2004
#'
#' Example reliability data set for two observers, binary data, from
#' Krippendorf (2004, Section 11.3.1, page 224). From the original:
#' TODO(jucor): cite Krippendorff 2004 properly
#'
#' \dQuote{The conceivably simplest reliability data are generated by two
#' observers who assign one of two available values to each of a common set of
#' units of analysis. For example, suppose a political scientist is interested
#' in references to the United States in the Chinese press and, unable to read
#' Chinese, hires two individuals (Jon and Han) who claim to be competent
#' readers of Chinese to identify the presence or absence of such references.
#' They mark each newspaper article "0" for absent or "1" for present.}
#'
#' @seealso \code{\link{news_presence_wide}}
#' @format A data frame with 10 rows and 3 variables:
#' \describe{
#' \item{article}{Article observed.}
#' \item{observer}{Name of the observer.}
#' \item{presence}{Indicator of observed presence of reference to the United
#' States.}
#' }
"news_presence"
