# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bootstrap_within_unit <- function(deviations, nboot) {
  .Call(`_krippendorff_bootstrap_within_unit`, deviations, nboot)
}

count_nominal <- function(n) {
  .Call(`_krippendorff_count_nominal`, n)
}
